### ISSUE TITLE
Feedback for "Calculation Views (.hdbcalculationview)"

### ISSUE THREAD

**Issue by FerneyAng** [SAP-docs/sap-hana-cloud-hana-database#9]
https://help.sap.com/docs/HANA_CLOUD_DATABASE/c2cc2e43458d4abda6788049c58143dc/3db2a35e714e4f6e9711fb62997d0c5c.html

I've configured all to use custom views, but when I tried to create a custom view, the editor didn't load:

![image](https://user-images.githubusercontent.com/37518466/213230702-0e53b6d4-77dc-4bbf-a5f2-8fb0afa387dd.png)

**Comment by jzwickel** [comment]
Does clearing your browser cache and reloading the page solve the issue?

**Comment by gn-sap** [comment]
Please also check the the calculation view is valid XML and try opening the view in the code/text editor.

**Comment by gn-sap** [comment]
Since this issue seems to be more related to database modelling and tools (for example, the calculation-view editor in SAP Business Application Studio or SAP Web IDE Full-stack) and not with the ".hdbcalculationview" database artifact-definition itself, there is nothing we can do to this topic. So I will close this issue.
